In [1]:
import pandas as pd
import numpy as np

In [2]:
print('loading files...')
dataset = pd.read_csv('total.csv', na_values=-1)
dataset.head()

loading files...

,Country.Name (imo.csv),Country.Name,Indicator.Code (edustats indicators.csv),Indicator.Code,Indicator.Name,Mean.Rank,Number of Records,Value
0,Kosovo,Kosovo,LO.PASEC.REA.6.P90,LO.PASEC.REA.6.P90,PASEC: Distribution of 6th grade reading score...,85.0,1,NaN
1,Kosovo,Kosovo,LO.PASEC.REA.6.P95,LO.PASEC.REA.6.P95,PASEC: Distribution of 6th grade reading score...,85.0,1,NaN
2,Kosovo,Kosovo,LO.PASEC.REA.6.P99,LO.PASEC.REA.6.P99,PASEC: Distribution of 6th grade reading score...,85.0,1,NaN
3,Kosovo,Kosovo,LO.PASEC.FRE5.FE,LO.PASEC.FRE5.FE,PASEC: Mean performance on the French language...,85.0,1,NaN
4,Kosovo,Kosovo,LO.PASEC.FRE5.MA,LO.PASEC.FRE5.MA,PASEC: Mean performance on the French language...,85.0,1,NaN

In [3]:
dataset.shape

(365620, 8)

In [4]:
dataset['Mean.Rank'].describe()

count    365620.000000
mean         54.648416
std          29.864960
min           1.630000
25%          27.750000
50%          52.380000
75%          80.130000
max         110.000000
Name: Mean.Rank, dtype: float64

In [5]:
data2=dataset.dropna()

In [6]:
data2.shape

(185402, 8)

In [7]:
data2.head(10)

,Country.Name (imo.csv),Country.Name,Indicator.Code (edustats indicators.csv),Indicator.Code,Indicator.Name,Mean.Rank,Number of Records,Value
497,Kosovo,Kosovo,SP.POP.GROW,SP.POP.GROW,Population growth (annual %),85.0,1,1.893806e-01
609,Kosovo,Kosovo,SP.POP.0014.TO.ZS,SP.POP.0014.TO.ZS,"Population, ages 0-14 (% of total)",85.0,1,2.747748e+01
610,Kosovo,Kosovo,SP.POP.0014.FE.IN,SP.POP.0014.FE.IN,"Population, ages 0-14, female",85.0,1,2.339580e+05
611,Kosovo,Kosovo,SP.POP.0014.MA.IN,SP.POP.0014.MA.IN,"Population, ages 0-14, male",85.0,1,2.539540e+05
612,Kosovo,Kosovo,SP.POP.0014.TO,SP.POP.0014.TO,"Population, ages 0-14, total",85.0,1,4.879120e+05
673,Kosovo,Kosovo,SP.POP.1564.TO.ZS,SP.POP.1564.TO.ZS,"Population, ages 15-64 (% of total)",85.0,1,6.587838e+01
674,Kosovo,Kosovo,SP.POP.1564.FE.IN,SP.POP.1564.FE.IN,"Population, ages 15-64, female",85.0,1,5.588990e+05
675,Kosovo,Kosovo,SP.POP.1564.MA.IN,SP.POP.1564.MA.IN,"Population, ages 15-64, male",85.0,1,6.108900e+05
676,Kosovo,Kosovo,SP.POP.1564.TO,SP.POP.1564.TO,"Population, ages 15-64, total",85.0,1,1.169789e+06
719,Kosovo,Kosovo,SP.POP.TOTL.FE.IN,SP.POP.TOTL.FE.IN,"Population, female",85.0,1,8.618450e+05

In [8]:
data2=data2.drop(["Number of Records","Country.Name (imo.csv)","Indicator.Code (edustats indicators.csv)","Indicator.Name"],axis=1)
data2

       Country.Name      Indicator.Code  Mean.Rank         Value
497          Kosovo         SP.POP.GROW      85.00  1.893806e-01
609          Kosovo   SP.POP.0014.TO.ZS      85.00  2.747748e+01
610          Kosovo   SP.POP.0014.FE.IN      85.00  2.339580e+05
611          Kosovo   SP.POP.0014.MA.IN      85.00  2.539540e+05
612          Kosovo      SP.POP.0014.TO      85.00  4.879120e+05
673          Kosovo   SP.POP.1564.TO.ZS      85.00  6.587838e+01
674          Kosovo   SP.POP.1564.FE.IN      85.00  5.588990e+05
675          Kosovo   SP.POP.1564.MA.IN      85.00  6.108900e+05
676          Kosovo      SP.POP.1564.TO      85.00  1.169789e+06
719          Kosovo   SP.POP.TOTL.FE.IN      85.00  8.618450e+05
720          Kosovo   SP.POP.TOTL.FE.ZS      85.00  4.853604e+01
721          Kosovo   SP.POP.TOTL.MA.IN      85.00  9.138350e+05
722          Kosovo   SP.POP.TOTL.MA.ZS      85.00  5.146396e+01
723          Kosovo         SP.POP.TOTL      85.00  1.745457e+06
1024        Albania          UIS.NERA.2      79.83  8.657743e+01
1025        Albania        UIS.NERA.2.F      79.83  8.602652e+01
1026        Albania      UIS.NERA.2.GPI      79.83  9.876075e-01
1027        Albania        UIS.NERA.2.M      79.83  8.710367e+01
1028        Albania         SE.PRM.TENR      79.83  9.317541e+01
1029        Albania      SE.PRM.TENR.FE      79.83  9.242793e+01
1030        Albania      UIS.NERA.1.GPI      79.83  9.902970e-01
1031        Albania      SE.PRM.TENR.MA      79.83  9.334111e+01
1032        Albania          UIS.NERA.3      79.83  6.886872e+01
1033        Albania        UIS.NERA.3.F      79.83  6.975758e+01
1034        Albania      UIS.NERA.3.GPI      79.83  1.025610e+00
1035        Albania        UIS.NERA.3.M      79.83  6.803381e+01
1036        Albania          UIS.NIRA.1      79.83  8.203633e+01
1037        Albania        UIS.NIRA.1.F      79.83  8.267640e+01
1038        Albania      UIS.NIRA.1.GPI      79.83  1.014818e+00
1039        Albania        UIS.NIRA.1.M      79.83  8.144237e+01
...             ...                 ...        ...           ...
365422       Kosovo     HH.MICS.OOST.DO      85.00  5.905543e+00
365423       Kosovo   HH.MICS.OOST.DO.F      85.00  1.398493e+01
365424       Kosovo   HH.MICS.OOST.DO.M      85.00  3.019721e+00
365425       Kosovo  HH.MICS.OOST.DO.Q1      85.00  3.907502e+00
365426       Kosovo  HH.MICS.OOST.DO.Q2      85.00  0.000000e+00
365427       Kosovo  HH.MICS.OOST.DO.Q3      85.00  2.482525e+01
365428       Kosovo  HH.MICS.OOST.DO.Q4      85.00  0.000000e+00
365429       Kosovo  HH.MICS.OOST.DO.Q5      85.00  6.956062e+00
365430       Kosovo   HH.MICS.OOST.DO.R      85.00  9.562646e+00
365431       Kosovo   HH.MICS.OOST.DO.U      85.00  1.395677e+00
365432       Kosovo      HH.MICS.OOST.L      85.00  8.830744e+01
365433       Kosovo    HH.MICS.OOST.L.F      85.00  8.601507e+01
365434       Kosovo    HH.MICS.OOST.L.M      85.00  9.698028e+01
365435       Kosovo   HH.MICS.OOST.L.Q1      85.00  7.605408e+01
365436       Kosovo   HH.MICS.OOST.L.Q2      85.00  1.000000e+02
365437       Kosovo   HH.MICS.OOST.L.Q3      85.00  7.517475e+01
365438       Kosovo   HH.MICS.OOST.L.Q4      85.00  1.000000e+02
365439       Kosovo   HH.MICS.OOST.L.Q5      85.00  9.304394e+01
365440       Kosovo    HH.MICS.OOST.L.R      85.00  9.043735e+01
365441       Kosovo    HH.MICS.OOST.L.U      85.00  8.608652e+01
365442       Kosovo      HH.MICS.OOST.X      85.00  5.787016e+00
365443       Kosovo    HH.MICS.OOST.X.F      85.00  0.000000e+00
365444       Kosovo    HH.MICS.OOST.X.M      85.00  0.000000e+00
365445       Kosovo   HH.MICS.OOST.X.Q1      85.00  2.003842e+01
365446       Kosovo   HH.MICS.OOST.X.Q2      85.00  0.000000e+00
365447       Kosovo   HH.MICS.OOST.X.Q3      85.00  0.000000e+00
365448       Kosovo   HH.MICS.OOST.X.Q4      85.00  0.000000e+00
365449       Kosovo   HH.MICS.OOST.X.Q5      85.00  0.000000e+00
365450       Kosovo    HH.MICS.OOST.X.R      85.00  0.000000e+00
365451       Kosovo    HH.MICS.OOST.X.U      85.00  1.251780e+01

[185402 rows x 4 columns]

In [9]:
data3=data2.pivot_table(index='Country.Name', columns='Indicator.Code', values='Value')
data3=data3.dropna(axis=1, how='any')
data3

Indicator.Code,NY.GDP.MKTP.CD,NY.GDP.PCAP.CD,NY.GNP.MKTP.CD,NY.GNP.PCAP.CD,SP.POP.GROW,SP.POP.TOTL
Country.Name,,,,,,
Albania,9.410937e+09,3189.768220,9.470301e+09,3157.333333,-0.478064,2.974934e+06
Algeria,1.317592e+11,3715.771082,1.291736e+11,3485.333333,1.569656,3.458545e+07
Argentina,3.302893e+11,8129.612822,3.211426e+11,7636.000000,1.062501,3.998689e+07
Armenia,7.091924e+09,2371.092082,7.411904e+09,2384.666667,-0.191634,3.006685e+06
Australia,9.086037e+11,41988.418643,8.780958e+11,38833.333333,1.432896,2.111886e+07
Austria,3.413169e+11,41084.585396,3.412290e+11,40639.333333,0.443092,8.272798e+06
Azerbaijan,3.532927e+10,3906.843289,3.260142e+10,3362.666667,1.184630,8.701051e+06
Bangladesh,9.349895e+10,628.909647,9.967268e+10,663.333333,1.410320,1.459843e+08
Belarus,4.205564e+10,4403.455346,4.133702e+10,4148.666667,-0.377188,9.637533e+06
Belgium,4.171766e+11,38798.870957,4.236881e+11,38968.000000,0.624815,1.068748e+07
Bolivia,1.625259e+10,1668.947508,1.551461e+10,1525.333333,1.701524,9.444894e+06
Bosnia and Herzegovina,1.350290e+10,3526.856489,1.392334e+10,3535.333333,0.058170,3.824734e+06
Botswana,1.061640e+10,5341.925232,1.011399e+10,5051.333333,1.746269,1.950931e+06
Brazil,1.458434e+12,7426.140273,1.409000e+12,6862.666667,1.160522,1.920199e+08
Bulgaria,3.859762e+10,5155.721158,3.753863e+10,4840.000000,-0.770468,7.608251e+06
Cambodia,9.014150e+09,638.043416,8.594250e+09,602.000000,1.671839,1.374601e+07
Canada,1.324657e+12,39673.515187,1.298239e+12,38042.000000,1.020409,3.302187e+07
Chile,1.649517e+11,9832.060624,1.549656e+11,8988.666667,1.135663,1.646493e+07
China,4.504389e+12,3372.849981,4.485603e+12,3206.666667,0.568602,1.316139e+09
Colombia,2.168574e+11,4791.598387,2.088927e+11,4442.666667,1.216629,4.426633e+07
Costa Rica,2.899786e+10,6519.606402,2.826086e+10,6195.333333,1.413351,4.360419e+06
Croatia,4.870967e+10,11127.914778,4.748237e+10,10628.666667,-0.287739,4.388442e+06
Cuba,5.217321e+10,4625.129947,4.748222e+10,4218.333333,0.177280,1.126882e+07
Cyprus,2.018092e+10,25582.564738,1.953004e+10,24328.666667,1.469124,1.056999e+06
Czech Republic,1.602765e+11,15436.443027,1.507477e+11,14150.666667,0.154738,1.034387e+07
Denmark,2.791778e+11,50791.760421,2.819903e+11,50542.000000,0.391257,5.478168e+06
Ecuador,5.576126e+10,3810.817455,5.428151e+10,3564.000000,1.659411,1.423303e+07
Egypt,1.630196e+11,2024.061788,1.612297e+11,1930.000000,1.925016,7.810738e+07
El Salvador,1.918106e+10,3200.511880,1.863666e+10,3090.666667,0.372658,5.976449e+06
Estonia,1.704867e+10,12742.159805,1.630904e+10,11692.000000,-0.326947,1.348383e+06
...,...,...,...,...,...,...
Philippines,1.574419e+11,1727.179173,1.948929e+11,2087.333333,1.746937,8.875372e+07
Poland,3.768319e+11,9887.910785,3.681232e+11,9488.666667,-0.112784,3.813664e+07
Portugal,2.023890e+11,19283.561834,1.975090e+11,18556.666667,0.118493,1.048092e+07
Puerto Rico,8.669723e+10,23119.635934,5.728375e+10,14984.285714,-0.482272,3.745308e+06
Romania,1.297790e+11,6312.645720,1.270230e+11,5896.000000,-0.807340,2.093189e+07
Russia,1.190558e+12,8290.327805,1.155346e+12,7448.666667,-0.155536,1.438556e+08
Saudi Arabia,4.354654e+11,16031.368108,4.418671e+11,15710.000000,2.627471,2.608971e+07
Serbia,3.242667e+10,4433.752012,3.169074e+10,4197.333333,-0.372556,7.358954e+06
Singapore,1.823751e+11,37671.785328,1.766852e+11,36031.333333,2.155378,4.676518e+06
Slovenia,4.010294e+10,19772.059379,3.970163e+10,19345.333333,0.260221,2.022348e+06
South Africa,2.729338e+11,5499.244035,2.661061e+11,5286.666667,1.537669,4.880451e+07
South Korea,9.548389e+11,19491.409249,9.549869e+11,19295.333333,0.523387,4.873084e+07
Spain,1.196554e+12,26633.516874,1.180054e+12,25887.333333,1.013378,4.442321e+07
Sri Lanka,4.004997e+10,2001.306713,3.939888e+10,1890.666667,0.760392,1.968053e+07
Sweden,4.308126e+11,46522.341534,4.407932e+11,47029.333333,0.602787,9.204287e+06
Switzerland,4.887362e+11,63455.680093,5.026410e+11,64023.333333,0.909849,7.620221e+06
Tajikistan,4.222438e+09,560.982825,4.306623e+09,540.000000,2.056192,7.152009e+06
Tanzania,2.437216e+10,567.810156,2.408267e+10,545.333333,2.981521,4.206109e+07
Thailand,2.590783e+11,3904.376617,2.488657e+11,3665.333333,0.591704,6.585313e+07
Trinidad and Tobago,1.865148e+10,14142.813631,1.732616e+10,12688.000000,0.456806,1.309754e+06
Tunisia,3.653022e+10,3532.426824,3.486365e+10,3394.000000,1.006315,1.025041e+07
Turkey,5.542021e+11,7782.385767,5.478905e+11,7571.333333,1.457958,6.984619e+07
Turkmenistan,1.759421e+10,3482.808859,1.634058e+10,3039.333333,1.175245,4.878088e+06
Uganda,1.407992e+10,440.885561,1.379989e+10,422.666667,3.301460,3.028428e+07
Ukraine,1.099343e+11,2386.619096,1.082124e+11,2233.333333,-0.605160,4.680421e+07
United Kingdom,2.361867e+12,38274.401707,2.379096e+12,38444.000000,0.641848,6.147592e+07
United States,1.379220e+13,45623.047792,1.398027e+13,46296.000000,0.890304,3.009444e+08
Uruguay,3.064800e+10,9092.268800,2.977529e+10,8538.666667,0.218379,3.354674e+06
Uzbekistan,2.847850e+10,1003.742223,2.925125e+10,999.333333,1.567898,2.730596e+07
Vietnam,9.135351e+10,1060.009087,8.815069e+10,976.666667,1.128813,8.418992e+07

In [10]:
# print(data2.groupby('Country.Name').agg(['mean', 'std', 'count']))

In [11]:
imoscore=pd.read_csv('Data/imo.csv')
imoscore.head()
combine=data3.merge(imoscore,  left_index=True, right_on='Country.Name', how='inner')
combine.head()

,NY.GDP.MKTP.CD,NY.GDP.PCAP.CD,NY.GNP.MKTP.CD,NY.GNP.PCAP.CD,SP.POP.GROW,SP.POP.TOTL,Country.Name,Mean.Rank
0,9.410937e+09,3189.768220,9.470301e+09,3157.333333,-0.478064,2.974934e+06,Albania,79.83
1,1.317592e+11,3715.771082,1.291736e+11,3485.333333,1.569656,3.458545e+07,Algeria,72.33
2,3.302893e+11,8129.612822,3.211426e+11,7636.000000,1.062501,3.998689e+07,Argentina,50.00
3,7.091924e+09,2371.092082,7.411904e+09,2384.666667,-0.191634,3.006685e+06,Armenia,43.88
4,9.086037e+11,41988.418643,8.780958e+11,38833.333333,1.432896,2.111886e+07,Australia,19.75

In [12]:
combine=combine[['Country.Name','NY.GDP.MKTP.CD','NY.GDP.PCAP.CD','NY.GNP.MKTP.CD','NY.GNP.PCAP.CD','SP.POP.GROW','SP.POP.TOTL','Mean.Rank']]
combine.head()

,Country.Name,NY.GDP.MKTP.CD,NY.GDP.PCAP.CD,NY.GNP.MKTP.CD,NY.GNP.PCAP.CD,SP.POP.GROW,SP.POP.TOTL,Mean.Rank
0,Albania,9.410937e+09,3189.768220,9.470301e+09,3157.333333,-0.478064,2.974934e+06,79.83
1,Algeria,1.317592e+11,3715.771082,1.291736e+11,3485.333333,1.569656,3.458545e+07,72.33
2,Argentina,3.302893e+11,8129.612822,3.211426e+11,7636.000000,1.062501,3.998689e+07,50.00
3,Armenia,7.091924e+09,2371.092082,7.411904e+09,2384.666667,-0.191634,3.006685e+06,43.88
4,Australia,9.086037e+11,41988.418643,8.780958e+11,38833.333333,1.432896,2.111886e+07,19.75

In [13]:
combine_new=combine.rename(index=str, columns={"Country.Name": "CName", 
                                               "NY.GDP.MKTP.CD": "GDPMKTP",
                                               "NY.GDP.PCAP.CD": "GDPPCAP",
                                               "NY.GNP.MKTP.CD": "GnpMKTP",
                                               "NY.GNP.PCAP.CD": "GnpPCAP",
                                              "SP.POP.GROW":"POPGrow",
                                              "SP.POP.TOTL":"POPTotal"})
combine_new

,CName,GDPMKTP,GDPPCAP,GnpMKTP,GnpPCAP,POPGrow,POPTotal,Mean.Rank
0,Albania,9.410937e+09,3189.768220,9.470301e+09,3157.333333,-0.478064,2.974934e+06,79.83
1,Algeria,1.317592e+11,3715.771082,1.291736e+11,3485.333333,1.569656,3.458545e+07,72.33
2,Argentina,3.302893e+11,8129.612822,3.211426e+11,7636.000000,1.062501,3.998689e+07,50.00
3,Armenia,7.091924e+09,2371.092082,7.411904e+09,2384.666667,-0.191634,3.006685e+06,43.88
4,Australia,9.086037e+11,41988.418643,8.780958e+11,38833.333333,1.432896,2.111886e+07,19.75
5,Austria,3.413169e+11,41084.585396,3.412290e+11,40639.333333,0.443092,8.272798e+06,51.00
6,Azerbaijan,3.532927e+10,3906.843289,3.260142e+10,3362.666667,1.184630,8.701051e+06,51.63
8,Bangladesh,9.349895e+10,628.909647,9.967268e+10,663.333333,1.410320,1.459843e+08,50.38
11,Belarus,4.205564e+10,4403.455346,4.133702e+10,4148.666667,-0.377188,9.637533e+06,28.25
7,Belgium,4.171766e+11,38798.870957,4.236881e+11,38968.000000,0.624815,1.068748e+07,51.75
12,Bolivia,1.625259e+10,1668.947508,1.551461e+10,1525.333333,1.701524,9.444894e+06,94.71
10,Bosnia and Herzegovina,1.350290e+10,3526.856489,1.392334e+10,3535.333333,0.058170,3.824734e+06,50.25
14,Botswana,1.061640e+10,5341.925232,1.011399e+10,5051.333333,1.746269,1.950931e+06,101.33
13,Brazil,1.458434e+12,7426.140273,1.409000e+12,6862.666667,1.160522,1.920199e+08,26.25
9,Bulgaria,3.859762e+10,5155.721158,3.753863e+10,4840.000000,-0.770468,7.608251e+06,25.00
48,Cambodia,9.014150e+09,638.043416,8.594250e+09,602.000000,1.671839,1.374601e+07,88.25
15,Canada,1.324657e+12,39673.515187,1.298239e+12,38042.000000,1.020409,3.302187e+07,13.13
16,Chile,1.649517e+11,9832.060624,1.549656e+11,8988.666667,1.135663,1.646493e+07,79.29
17,China,4.504389e+12,3372.849981,4.485603e+12,3206.666667,0.568602,1.316139e+09,1.63
18,Colombia,2.168574e+11,4791.598387,2.088927e+11,4442.666667,1.216629,4.426633e+07,55.00
19,Costa Rica,2.899786e+10,6519.606402,2.826086e+10,6195.333333,1.413351,4.360419e+06,65.88
35,Croatia,4.870967e+10,11127.914778,4.748237e+10,10628.666667,-0.287739,4.388442e+06,29.00
20,Cuba,5.217321e+10,4625.129947,4.748222e+10,4218.333333,0.177280,1.126882e+07,93.17
21,Cyprus,2.018092e+10,25582.564738,1.953004e+10,24328.666667,1.469124,1.056999e+06,64.88
22,Czech Republic,1.602765e+11,15436.443027,1.507477e+11,14150.666667,0.154738,1.034387e+07,37.38
23,Denmark,2.791778e+11,50791.760421,2.819903e+11,50542.000000,0.391257,5.478168e+06,64.38
24,Ecuador,5.576126e+10,3810.817455,5.428151e+10,3564.000000,1.659411,1.423303e+07,78.63
25,Egypt,1.630196e+11,2024.061788,1.612297e+11,1930.000000,1.925016,7.810738e+07,107.00
82,El Salvador,1.918106e+10,3200.511880,1.863666e+10,3090.666667,0.372658,5.976449e+06,85.86
27,Estonia,1.704867e+10,12742.159805,1.630904e+10,11692.000000,-0.326947,1.348383e+06,64.00
...,...,...,...,...,...,...,...,...
73,Philippines,1.574419e+11,1727.179173,1.948929e+11,2087.333333,1.746937,8.875372e+07,46.13
74,Poland,3.768319e+11,9887.910785,3.681232e+11,9488.666667,-0.112784,3.813664e+07,26.13
75,Portugal,2.023890e+11,19283.561834,1.975090e+11,18556.666667,0.118493,1.048092e+07,44.88
76,Puerto Rico,8.669723e+10,23119.635934,5.728375e+10,14984.285714,-0.482272,3.745308e+06,85.25
77,Romania,1.297790e+11,6312.645720,1.270230e+11,5896.000000,-0.807340,2.093189e+07,15.25
78,Russia,1.190558e+12,8290.327805,1.155346e+12,7448.666667,-0.155536,1.438556e+08,5.50
80,Saudi Arabia,4.354654e+11,16031.368108,4.418671e+11,15710.000000,2.627471,2.608971e+07,46.50
83,Serbia,3.242667e+10,4433.752012,3.169074e+10,4197.333333,-0.372556,7.358954e+06,24.25
81,Singapore,1.823751e+11,37671.785328,1.766852e+11,36031.333333,2.155378,4.676518e+06,8.38
85,Slovenia,4.010294e+10,19772.059379,3.970163e+10,19345.333333,0.260221,2.022348e+06,61.13
79,South Africa,2.729338e+11,5499.244035,2.661061e+11,5286.666667,1.537669,4.880451e+07,56.25
49,South Korea,9.548389e+11,19491.409249,9.549869e+11,19295.333333,0.523387,4.873084e+07,4.13
26,Spain,1.196554e+12,26633.516874,1.180054e+12,25887.333333,1.013378,4.442321e+07,54.63
52,Sri Lanka,4.004997e+10,2001.306713,3.939888e+10,1890.666667,0.760392,1.968053e+07,64.25
86,Sweden,4.308126e+11,46522.341534,4.407932e+11,47029.333333,0.602787,9.204287e+06,57.75
84,Switzerland,4.887362e+11,63455.680093,5.026410e+11,64023.333333,0.909849,7.620221e+06,44.75
88,Tajikistan,4.222438e+09,560.982825,4.306623e+09,540.000000,2.056192,7.152009e+06,53.88
93,Tanzania,2.437216e+10,567.810156,2.408267e+10,545.333333,2.981521,4.206109e+07,104.25
87,Thailand,2.590783e+11,3904.376617,2.488657e+11,3665.333333,0.591704,6.585313e+07,10.00
90,Trinidad and Tobago,1.865148e+10,14142.813631,1.732616e+10,12688.000000,0.456806,1.309754e+06,86.38
91,Tunisia,3.653022e+10,3532.426824,3.486365e+10,3394.000000,1.006315,1.025041e+07,77.50
92,Turkey,5.542021e+11,7782.385767,5.478905e+11,7571.333333,1.457958,6.984619e+07,18.00
89,Turkmenistan,1.759421e+10,3482.808859,1.634058e+10,3039.333333,1.175245,4.878088e+06,54.00
94,Uganda,1.407992e+10,440.885561,1.379989e+10,422.666667,3.301460,3.028428e+07,96.83
95,Ukraine,1.099343e+11,2386.619096,1.082124e+11,2233.333333,-0.605160,4.680421e+07,16.63
96,United Kingdom,2.361867e+12,38274.401707,2.379096e+12,38444.000000,0.641848,6.147592e+07,16.38
98,United States,1.379220e+13,45623.047792,1.398027e+13,46296.000000,0.890304,3.009444e+08,2.38
97,Uruguay,3.064800e+10,9092.268800,2.977529e+10,8538.666667,0.218379,3.354674e+06,88.86
99,Uzbekistan,2.847850e+10,1003.742223,2.925125e+10,999.333333,1.567898,2.730596e+07,60.20
100,Vietnam,9.135351e+10,1060.009087,8.815069e+10,976.666667,1.128813,8.418992e+07,10.88

In [14]:
train = combine_new
X = train.drop(['CName','Mean.Rank'], axis=1).values
y = train['Mean.Rank'].values

In [15]:
from sklearn.linear_model import LinearRegression, Ridge, ElasticNet, Lasso,  BayesianRidge, LassoLarsIC
from sklearn.ensemble import RandomForestRegressor,  GradientBoostingRegressor
from sklearn.kernel_ridge import KernelRidge
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xgb
import lightgbm as lgb

/Anaconda/anaconda/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [16]:
train = X[:71]
test = X[71:]
y_train = y

In [17]:
#Validation function
n_folds = 5

def rmsle_cv(model):
    kf = KFold(n_folds, shuffle=True, random_state=42).get_n_splits(X)
    rmse= np.sqrt(-cross_val_score(model, X, y_train, scoring="neg_mean_squared_error", cv = kf))
    return(rmse)

In [18]:
linreg = LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)
ridgereg = Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)
lasso = make_pipeline(RobustScaler(), Lasso(alpha =0.0005, max_iter = 10000000, random_state=1))
ENet = make_pipeline(RobustScaler(), ElasticNet(alpha=0.0005, max_iter = 10000000, l1_ratio=.9, random_state=3))
KRR = KernelRidge(alpha=0.6, kernel='polynomial', degree=2, coef0=2.5)
GBoost = GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05,
                                   max_depth=4, max_features='sqrt',
                                   min_samples_leaf=15, min_samples_split=10, 
                                   loss='huber', random_state =5)
model_xgb = xgb.XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, 
                             learning_rate=0.05, max_depth=3, 
                             min_child_weight=1.7817, n_estimators=2200,
                             reg_alpha=0.4640, reg_lambda=0.8571,
                             subsample=0.5213, silent=1, nthread = -1)
model_lgb = lgb.LGBMRegressor(objective='regression',num_leaves=5,
                              learning_rate=0.05, n_estimators=720,
                              max_bin = 55, bagging_fraction = 0.8,
                              bagging_freq = 5, feature_fraction = 0.2319,
                              feature_fraction_seed=9, bagging_seed=9,
                              min_data_in_leaf =6, min_sum_hessian_in_leaf = 11)

In [19]:
score = rmsle_cv(linreg)
print("\nreg score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

reg score: 29.1154 (8.7628)

In [20]:
score = rmsle_cv(ridgereg)
print("\nridgereg score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

ridgereg score: 29.1063 (8.7445)

In [21]:
score = rmsle_cv(lasso)
print("\nLasso score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

Lasso score: 29.0794 (8.7103)

In [22]:
score = rmsle_cv(ENet)
print("ElasticNet score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

ElasticNet score: 28.5587 (7.9907)

In [23]:
score = rmsle_cv(GBoost)
print("Gradient Boosting score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

Gradient Boosting score: 23.1716 (4.9569)

In [24]:
score = rmsle_cv(model_xgb)
print("Xgboost score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))

Xgboost score: 20.6616 (3.1002)

In [25]:
score = rmsle_cv(model_lgb)
print("LGBM score: {:.4f} ({:.4f})\n" .format(score.mean(), score.std()))

LGBM score: 23.2653 (3.1958)

In [26]:
# score = rmsle_cv(KRR)
# print("Kernel Ridge score: {:.4f} ({:.4f})\n".format(score.mean(), score.std()))
#comment due to this block will have 'singular matrix error' problem
#RuntimeWarning: scipy.linalg.solve Ill-conditioned matrix detected. Result is not guaranteed to be accurate

In [27]:
combine_new.describe()

,GDPMKTP,GDPPCAP,GnpMKTP,GnpPCAP,POPGrow,POPTotal,Mean.Rank
count,1.010000e+02,101.000000,1.010000e+02,101.000000,101.000000,1.010000e+02,101.000000
mean,5.253302e+11,15722.414863,5.257771e+11,14743.444988,0.898732,5.889643e+07,54.648416
std,1.561320e+12,20611.690676,1.581357e+12,18554.875495,0.947926,1.776479e+08,30.013872
min,3.087337e+09,440.885561,3.140551e+09,422.666667,-1.225695,3.539187e+04,1.630000
25%,2.289899e+10,2376.904759,2.234440e+10,2272.000000,0.189381,4.676518e+06,27.750000
50%,1.110890e+11,6312.645720,1.065114e+11,5586.666667,1.013378,1.126882e+07,52.380000
75%,3.302893e+11,23119.635934,3.269764e+11,21840.000000,1.495713,4.442321e+07,80.130000
max,1.379220e+13,113818.255193,1.398027e+13,90211.000000,3.301460,1.316139e+09,110.000000

# try to use more features, say all the features with lest than 80 NaN values

In [28]:
data2.head()
# data2.shape (185402, 4)

    Country.Name     Indicator.Code  Mean.Rank          Value
497       Kosovo        SP.POP.GROW       85.0       0.189381
609       Kosovo  SP.POP.0014.TO.ZS       85.0      27.477477
610       Kosovo  SP.POP.0014.FE.IN       85.0  233958.000000
611       Kosovo  SP.POP.0014.MA.IN       85.0  253954.000000
612       Kosovo     SP.POP.0014.TO       85.0  487912.000000

In [29]:
data4=data2.pivot_table(index='Country.Name', columns='Indicator.Code', values='Value')
data4=data4.dropna(axis=1, thresh=50)
data4.head()

Indicator.Code,BAR.NOED.1519.FE.ZS,BAR.NOED.1519.ZS,BAR.NOED.15UP.FE.ZS,BAR.NOED.15UP.ZS,BAR.NOED.2024.FE.ZS,BAR.NOED.2024.ZS,BAR.NOED.2529.FE.ZS,BAR.NOED.2529.ZS,BAR.NOED.25UP.FE.ZS,BAR.NOED.25UP.ZS,...,UIS.XUNIT.US.23.FSGOV,UIS.XUNIT.US.3.FSGOV,UIS.XUNIT.US.56.FSGOV,UIS.XUNIT.USCONST.1.FSGOV,UIS.XUNIT.USCONST.2.FSGOV,UIS.XUNIT.USCONST.23.FSGOV,UIS.XUNIT.USCONST.3.FSGOV,UIS.XUNIT.USCONST.56.FSGOV,XGDP.23.FSGOV.FDINSTADM.FFD,XGDP.56.FSGOV.FDINSTADM.FFD
Country.Name,,,,,,,,,,,,,,,,,,,,,
Albania,0.960000,1.146667,3.056667,2.300000,1.190000,1.263333,1.056667,1.126667,3.656667,2.630000,...,258.907440,176.931961,573.089600,1294.434082,324.860687,258.907440,176.931961,573.089600,0.701640,0.775850
Algeria,8.536667,6.533333,34.973333,26.296667,11.343333,7.120000,15.546667,10.040000,44.336667,33.650000,...,333.231283,488.660179,NaN,486.116252,654.020121,794.764160,1034.755646,NaN,1.821173,NaN
Argentina,0.376667,0.476667,1.956667,1.756667,0.540000,0.600000,0.873333,0.890000,2.423333,2.156667,...,1505.204237,1592.533236,1229.963848,1403.893367,1884.196442,1973.816738,2122.200989,1618.617541,1.626836,0.749662
Armenia,0.160000,0.943333,0.646667,0.566667,0.110000,0.236667,0.110000,0.163333,0.786667,0.570000,...,582.196309,712.477783,260.542546,486.168045,496.355937,582.714193,712.700195,261.332761,1.333313,0.228587
Australia,0.136667,0.153333,1.016667,0.903333,0.186667,0.196667,0.313333,0.310000,1.146667,1.016667,...,8232.155347,7526.610522,9923.463525,11972.454199,11788.698828,11011.268652,10108.025342,13524.003320,1.699275,0.744217

In [30]:
# data4.loc['Kosovo','SP.POP.GROW']

In [31]:
count=data4.std()>0
count.sum()

1822

In [32]:
# data4.sort_values(by='BAR.NOED.1519.FE.ZS', ascending=False)